name: vlc_flutter_compat
description: This is a Flutter wrapper plugin for libvlc.
version: 0.0.1
homepage: https://github.com/arcticfox1919/vlc-flutter

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pigeon: ^9.0.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: xyz.bczl.vlc_flutter_compat
        pluginClass: VlcFlutterPlugin
      ios:
        pluginClass: VlcFlutterPlugin
